version: '3'

services:
    dynamodb:
        image: amazon/dynamodb-local
        expose:
            - 8000
        ports:
            - 8000:8000
    dynamodb-admin:
        image: aaronshaf/dynamodb-admin
        expose:
            - 8001
        ports:
            - 8001:8001
        environment:
            - DYNAMO_ENDPOINT=http://dynamodb:8000
