AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  emosearch-api

  SAM Template for emosearch-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        GOOGLE_SERVICE_ACCOUNT_KEY: ""
        AWS_ENDPOINT: ""
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      MaxAge: "'600'"
      AllowCredentials: False

Resources:
  EmosearchAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: cmd/emosearch-api
      Handler: emosearch-api
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchGet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /v1/{proxy+}
            Method: GET
        CatchPost:
          Type: Api
          Properties:
            Path: /v1/{proxy+}
            Method: POST
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref GoogleServiceAccountKey
  EmosearchBatchSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: cmd/batch-search
      Handler: batch-search
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchGet:
          Type: Schedule
          Properties:
            Schedule: rate(15 minutes)
            Name: emosearch-api-batch-search-schedule
            Description: Scheduling batch search
            Enabled: True
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Ref GoogleServiceAccountKey
  GoogleServiceAccountKey:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: GoogleServiceAccountKey
      SecretString:
        PleaseInputByAdmin

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  EmosearchAPIFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt EmosearchAPIFunction.Arn
  EmosearchAPIFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt EmosearchAPIFunctionRole.Arn
